/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    Card: typeof import('./src/components/Card.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    OutlineBadge: typeof import('./src/components/OutlineBadge.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
